
set(TEST_GIT_REPO /data/OpenCMISS/examples/monodomain_2D_vary_parameters_spatially)
set(TEST_BRANCH develop)
set(PYTEST_MULTI_PROCESS True)
set(PYTEST_NP 4)
set(PYTEST_TARGETS src/python/monodomain_2D_vary_parameters_spatially.py)
#set(PYTEST_TARGETS_ARGS "src/python/n98.xml")
set(PYTEST_EXPECTED_RESULTS src/python/expected_results/)
set(PYTEST_ABS_TOLERANCE 1e-11)
set(PYTEST_REL_TOLERANCE 1e-11)
